<MealsScreen@MDFloatLayout>:
    MDCard:
        size_hint: .9, .8
        pos_hint: {"x": .05, "y": .2}
        size_hint_y: .85
        elevation: 0
        orientation: 'vertical'

        MDBoxLayout:
            orientation: 'vertical'
            padding: dp(15)
            MDLabel:
                text: "Foods:"
                size_hint_y: .1

            MDBoxLayout:
                id: my_foods_layout

    MDBoxLayout:
        size_hint: 1, 0.15
        pos_hint: {"x": .5, "y": 0.1}
        spacing: dp(10)
        MDFabButton:
            icon: "delete"
            on_release: app.on_delete_foods_pressed(*args)
        MDFabButton:
            icon: "plus"
            on_release: app.on_add_food_pressed(*args)
        MDFabButton:
            icon: "magnify"
            on_release: app.on_search_food_pressed(*args)
