#:import toast calorie_count.src.utils.kivy_components.toast
<ContentNavigationDrawer@MDBoxLayout>:
    orientation: "vertical"
    padding: "8dp"
    spacing: "8dp"

    AnchorLayout:
        anchor_x: "left"
        size_hint_y: None
        height: avatar.height

        Image:
            id: avatar
            size_hint: None, None
            size: "56dp", "56dp"
            source: "src/cc.jpg"

    MDLabel:
        text: "Calorie Counter"
        font_style: "Title"
        adaptive_height: True

    MDLabel:
        text: "By: Efrayim Sztokman"
        font_style: "Label"
        adaptive_height: True

    ScrollView:
        MDList:
            MDListItem:
                on_release: toast('Not Implemented yet')
                MDListItemLeadingIcon:
                    icon: "scan-helper"
                MDListItemHeadlineText:
                    text: "Capture Label"
            MDListItem:
                on_release: toast('Not Implemented yet')
                MDListItemLeadingIcon:
                    icon: "account"
                MDListItemHeadlineText:
                    text: "User"
            MDListItem:
                on_release: toast('Not Implemented yet')
                MDListItemLeadingIcon:
                    icon: "calendar-month"
                MDListItemHeadlineText:
                    text: "Meal Plan"
            MDListItem:
                on_release: toast('Not Implemented yet')
                MDListItemLeadingIcon:
                    icon: "checkbox-marked"
                MDListItemHeadlineText:
                    text: "Daily Goals"
