<TrendsScreen@MDBoxLayout>:
    orientation: 'vertical'
    MDBoxLayout:
        size_hint: 1, .1
        pos_hint: {'y': .98}
        spacing: dp(5)
        padding: dp(5)
        MDButton:
            id: trend_start_date_button
            style: "tonal"
            size_hint_y: .8
            on_release: app.show_date_picker(*args)
            MDButtonText:
                text: "Start Date:"
        MDButton:
            id: trend_end_date_button
            style: "tonal"
            size_hint_y: .8
            on_release: app.show_date_picker(*args)
            MDButtonText:
                text: "End Date:"
        MDButton:
            style: "filled"
            size_hint_y: .8
            on_release: app.generate_trend(*args)
            MDButtonIcon:
                icon: 'chart-box'
            MDButtonText:
                text: "Create"
    MDBoxLayout:
        size_hint: 1, .12
        spacing: dp(5)
        padding: dp(5)
        MDButton:
            style: "outlined"
            on_release: app.set_trends_date_range(days_back=0)
            MDButtonIcon:
                icon: 'calendar'
            MDButtonText:
                text: "today"
        MDButton:
            style: "outlined"
            on_release: app.set_trends_date_range(days_back=7)
            MDButtonIcon:
                icon: 'calendar-range'
            MDButtonText:
                text: "week"
        MDButton:
            style: "outlined"
            on_release: app.set_trends_date_range(days_back=30)
            MDButtonIcon:
                icon: 'calendar-month'
            MDButtonText:
                text: "month"
    MDBoxLayout:
        padding: dp(40)
        ScrollView:
            do_scroll_y: True
            MDBoxLayout:
                spacing: dp(5)
                size_hint_y: 1.5
                orientation: 'vertical'
                id: trends_layout
